### ISSUE TITLE
does not work with Scala 3.0.0-M2, sbt-dotty 0.4.6

### ISSUE THREAD

**Issue by xuwei-k** [sbt/sbt-unidoc#83]
- https://github.com/xuwei-k/unidoc-scala-3/runs/1472124231
- https://github.com/xuwei-k/unidoc-scala-3/commit/d66926cb70ecd41f7202d4634d567b7976ab4bd1

```diff
--- /dev/null
+++ b/a1/A.scala
@@ -0,0 +1 @@
+class A
diff --git a/a2/B.scala b/a2/B.scala
new file mode 100644
index 0000000..179f0d2
--- /dev/null
+++ b/a2/B.scala
@@ -0,0 +1 @@
+class B
diff --git a/build.sbt b/build.sbt
new file mode 100644
index 0000000..57221b1
--- /dev/null
+++ b/build.sbt
@@ -0,0 +1,16 @@
+val commonSettings = Def.settings(
+  organization := "com.example",
+  version := "0.1.0-SNAPSHOT",
+  scalaVersion := "3.0.0-M2",
+)
+
+val a1 = project.settings(
+  commonSettings,
+)
+
+val a2 = project.settings(
+  commonSettings,
+)
+
+commonSettings
+enablePlugins(ScalaUnidocPlugin)
diff --git a/project/build.properties b/project/build.properties
new file mode 100644
index 0000000..7de0a93
--- /dev/null
+++ b/project/build.properties
@@ -0,0 +1 @@
+sbt.version=1.4.4
diff --git a/project/plugins.sbt b/project/plugins.sbt
new file mode 100644
index 0000000..6e5893d
--- /dev/null
+++ b/project/plugins.sbt
@@ -0,0 +1,2 @@
+addSbtPlugin("com.eed3si9n" % "sbt-unidoc" % "0.4.3")
+addSbtPlugin("ch.epfl.lamp" % "sbt-dotty" % "0.4.6")
```

run `sbt unidoc`

```
[info] Main Scala API documentation to /home/runner/work/unidoc-scala-3/unidoc-scala-3/target/scala-3.0.0-M2/unidoc...
[error] java.lang.RuntimeException: java.lang.ClassNotFoundException: dotty.tools.dottydoc.Main
[error] 	at xsbt.DottydocRunner.run(DottydocRunner.java:85)
[error] 	at xsbt.ScaladocInterface.run(ScaladocInterface.java:11)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.internal.inc.AnalyzingCompiler.invoke(AnalyzingCompiler.scala:330)
[error] 	at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:176)
[error] 	at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:134)
[error] 	at sbt.Doc$.$anonfun$scaladoc$1(Doc.scala:52)
[error] 	at sbt.Doc$.$anonfun$scaladoc$1$adapted(Doc.scala:40)
[error] 	at sbt.RawCompileLike$.$anonfun$prepare$1(RawCompileLike.scala:79)
[error] 	at sbt.RawCompileLike$.$anonfun$prepare$1$adapted(RawCompileLike.scala:72)
[error] 	at sbt.RawCompileLike$.$anonfun$cached$4(RawCompileLike.scala:63)
[error] 	at sbt.RawCompileLike$.$anonfun$cached$4$adapted(RawCompileLike.scala:61)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error] 	at sbt.RawCompileLike$.$anonfun$cached$1(RawCompileLike.scala:68)
[error] 	at sbt.RawCompileLike$.$anonfun$cached$1$adapted(RawCompileLike.scala:52)
[error] 	at sbtunidoc.Unidoc$.apply(Unidoc.scala:30)
[error] 	at sbtunidoc.BaseUnidocPlugin$.$anonfun$baseUnidocSettings$1(BaseUnidocPlugin.scala:25)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] Caused by: java.lang.ClassNotFoundException: dotty.tools.dottydoc.Main
[error] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[error] 	at java.lang.Class.forName0(Native Method)
[error] 	at java.lang.Class.forName(Class.java:264)
[error] 	at xsbt.DottydocRunner.run(DottydocRunner.java:79)
[error] 	at xsbt.ScaladocInterface.run(ScaladocInterface.java:11)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.internal.inc.AnalyzingCompiler.invoke(AnalyzingCompiler.scala:330)
[error] 	at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:176)
[error] 	at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:134)
[error] 	at sbt.Doc$.$anonfun$scaladoc$1(Doc.scala:52)
[error] 	at sbt.Doc$.$anonfun$scaladoc$1$adapted(Doc.scala:40)
[error] 	at sbt.RawCompileLike$.$anonfun$prepare$1(RawCompileLike.scala:79)
[error] 	at sbt.RawCompileLike$.$anonfun$prepare$1$adapted(RawCompileLike.scala:72)
[error] 	at sbt.RawCompileLike$.$anonfun$cached$4(RawCompileLike.scala:63)
[error] 	at sbt.RawCompileLike$.$anonfun$cached$4$adapted(RawCompileLike.scala:61)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error] 	at sbt.RawCompileLike$.$anonfun$cached$1(RawCompileLike.scala:68)
[error] 	at sbt.RawCompileLike$.$anonfun$cached$1$adapted(RawCompileLike.scala:52)
[error] 	at sbtunidoc.Unidoc$.apply(Unidoc.scala:30)
[error] 	at sbtunidoc.BaseUnidocPlugin$.$anonfun$baseUnidocSettings$1(BaseUnidocPlugin.scala:25)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (Scalaunidoc / doc) java.lang.ClassNotFoundException: dotty.tools.dottydoc.Main
```

**Comment by TimWSpence** [comment]
I was just wondering if anyone is looking at this? I appreciate it may not be high priority but I _think_ I followed mdoc's advice in using unidoc with docusaurus and I'm currently blocked on supporting 3.0.0-M3 in cats-stm because I can't publish the microsite 😭 

I don't know much about sbt at all but let me know if there's something I can do to help!

**Comment by eed3si9n** [comment]
@adpi2 at Scala Center is currently working to merge sbt-dotty into sbt (https://github.com/sbt/sbt/issues/6080), and VirtusLab is reworking scaladoc (aka scala3doc), so I don't think it's worth looking at it now. After the dust is settled the fix should be fairly simple to setup the classloader or whatever correctly.

**Comment by TimWSpence** [comment]
OK thanks @eed3si9n! Is https://github.com/sbt/sbt/issues/6080 the issue I should watch for updates on this? Or where would you recommend following?

**Comment by adpi2** [comment]
@TimWSpence can you reproduce the bug on a nightly version of sbt?

```scala
// project/build.properties
sbt.version=1.5.0-bin-20210105T082608
```

**Comment by TimWSpence** [comment]
@adpi2 thanks! Sorry for the very slow reply, I've only just got round to looking at this again. Turns out that I never had `sbt-dotty` enabled in the first place 🤦 I'm not sure why I never had a problem before 3.0.0-M3 but enabling the dotty plugin with sbt 1.4.7 has fixed it for the moment
